# Generated by Django 3.0.8 on 2020-07-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
