# Generated by Django 3.0.8 on 2020-07-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200725_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_and_street',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='occupied',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
