# Generated by Django 3.0.8 on 2020-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_property_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='movein',
            field=models.DateField(default=-2020),
            preserve_default=False,
        ),
    ]
