# Generated by Django 3.0.8 on 2020-07-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_property_movein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='movein',
        ),
    ]
